steps:
  # Build the Docker image as below
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/quixotic-prism-412316/assignment2/myflask_app:${COMMIT_SHA}', '.']
  # Push the Docker image to the artifact registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/quixotic-prism-412316/assignment2/myflask_app:${COMMIT_SHA}']
  # Deploy the Docker container to Google Compute Engine instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instances update-container airhunde1-vm \
          --container-image us-east1-docker.pkg.dev/quixotic-prism-412316/assignment2/myflask_app:${COMMIT_SHA} \
          --zone us-east1-b
options:
  # Set defaultLogsBucketBehavior to REGIONAL_USER_OWNED_BUCKET
  # defaultLogsBucket: 'gs://your-build-logs-bucket' # Replace with your build logs bucket
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'
 
images:
# Store images in Google Artifact Registry
  - us-east1-docker.pkg.dev/quixotic-prism-412316/assignment2/myflask_app:${COMMIT_SHA}
